# Generated by Django 4.2.7 on 2024-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('editor', 'Editor')], default='subscriber', max_length=10),
        ),
    ]
